const crypto = require('crypto');
const { getParserForLanguage } = require('../parsers');
const { extractSymbols } = require('./analysis/symbolExtractor');
const { analyzeSymbolComments, detectFileDocumentationStyle } = require('./analysis/commentAnalyzer');
const { scoreAllSymbols } = require('./analysis/documentationScorer');
const { analyzeCandidateSymbols } = require('./ai/documentationAgent');
const { applyCommentPatches } = require('./patch/commentPatch.service');
const { validateTransformation } = require('./validation/result.validator');
const { sanitizeFilename } = require('../utils/filename.utils');
const { isSupportedLanguage } = require('../utils/language.utils');
const logger = require('../utils/logger');

const MAX_CODE_SIZE_BYTES = 200 * 1024;

async function analyzeCode({
  filename,
  language,
  code,
  mode = 'recommended',
  threshold,
  autoApplyConfidence,
}) {
  const startTime = Date.now();
  const requestId = crypto.randomUUID().slice(0, 8);

  if (!code || typeof code !== 'string' || code.trim().length === 0) {
    throw Object.assign(new Error('Code is required and cannot be empty.'), {
      statusCode: 400,
    });
  }

  const byteLength = Buffer.byteLength(code, 'utf-8');
  if (byteLength > MAX_CODE_SIZE_BYTES) {
    throw Object.assign(
      new Error(`Code exceeds the maximum allowed size of ${MAX_CODE_SIZE_BYTES / 1024} KB.`),
      { statusCode: 400 }
    );
  }

  if (!language || !isSupportedLanguage(language)) {
    throw Object.assign(
      new Error(
        `Unsupported language "${language}". Supported: javascript, typescript, jsx, tsx, java, python.`
      ),
      { statusCode: 400 }
    );
  }

  const safeFilename = sanitizeFilename(filename);
  const langKey = language.toLowerCase();

  const isGenerated =
    safeFilename.includes('.min.') ||
    safeFilename.includes('.generated.') ||
    code.slice(0, 500).includes('@generated') ||
    code.slice(0, 500).includes('DO NOT EDIT') ||
    code.slice(0, 500).includes('<auto-generated>');

  if (isGenerated) {
    return {
      success: true,
      filename: safeFilename,
      language: langKey,
      stats: {
        symbolsFound: 0,
        symbolsAnalyzed: 0,
        commentsAdded: 0,
        commentsSkipped: 0,
      },
      validation: {
        syntaxValid: true,
        logicPreserved: true,
        commentOnlyChanges: true,
      },
      changes: [],
      originalCode: code,
      updatedCode: code,
      diff: '',
      isGenerated: true,
    };
  }

  const parser = getParserForLanguage(langKey);

  const initialSyntaxCheck = parser.validate(code);
  if (!initialSyntaxCheck.valid) {
    throw Object.assign(
      new Error(`Source code has syntax errors: ${initialSyntaxCheck.errors.join(', ')}`),
      { statusCode: 400 }
    );
  }

  const { symbols: rawSymbols, ast: originalAst, comments, fileMetadata } = extractSymbols(
    code,
    langKey
  );

  const symbolsWithComments = analyzeSymbolComments(rawSymbols, comments);
  const scoredSymbols = scoreAllSymbols(symbolsWithComments, { mode, threshold });

  const preferredStyle = detectFileDocumentationStyle(comments);

  const candidatesToAnalyze = scoredSymbols.filter((s) => s.recommendation === 'DOCUMENT');

  let aiInstructions = [];
  try {
    aiInstructions = await analyzeCandidateSymbols({
      symbols: candidatesToAnalyze,
      language: langKey,
      filename: safeFilename,
      preferredStyle,
      fileMetadata,
      options: { autoApplyConfidence },
    });
  } catch (err) {
    logger.error({
      requestId,
      language: langKey,
      fileSize: byteLength,
      extra: `AI Analysis Error: ${err.message}`,
    });
    throw Object.assign(new Error(`AI documentation analysis failed: ${err.message}`), {
      statusCode: 502,
    });
  }

  const { updatedCode, appliedChanges, skippedChanges } = applyCommentPatches({
    originalCode: code,
    instructions: aiInstructions,
    symbols: scoredSymbols,
    parser,
  });

  const updatedAst = parser.parse(updatedCode);

  const validation = validateTransformation({
    originalCode: code,
    updatedCode,
    originalAst,
    updatedAst,
    language: langKey,
    parser,
  });

  if (!validation.valid) {
    logger.error({
      requestId,
      language: langKey,
      fileSize: byteLength,
      symbolsFound: scoredSymbols.length,
      symbolsAnalyzed: candidatesToAnalyze.length,
      commentsAdded: appliedChanges.length,
      validationResult: 'REJECTED',
      extra: `Errors: ${validation.errors.join('; ')}`,
    });

    throw Object.assign(
      new Error(`AST / Safety validation failed: ${validation.errors.join('; ')}`),
      { statusCode: 422 }
    );
  }

  const durationMs = Date.now() - startTime;
  const skippedCount = scoredSymbols.length - appliedChanges.length;

  logger.info({
    requestId,
    language: langKey,
    fileSize: byteLength,
    symbolsFound: scoredSymbols.length,
    symbolsAnalyzed: candidatesToAnalyze.length,
    commentsAdded: appliedChanges.length,
    aiLatencyMs: durationMs,
    validationResult: 'PASSED',
  });

  const allChanges = [
    ...appliedChanges,
    ...skippedChanges,
  ];

  return {
    success: true,
    filename: safeFilename,
    language: langKey,
    stats: {
      symbolsFound: scoredSymbols.length,
      symbolsAnalyzed: candidatesToAnalyze.length,
      commentsAdded: appliedChanges.length,
      commentsSkipped: skippedCount > 0 ? skippedCount : 0,
    },
    validation: {
      syntaxValid: validation.syntaxValid,
      logicPreserved: validation.logicPreserved,
      commentOnlyChanges: validation.commentOnlyChanges,
    },
    changes: allChanges,
    originalCode: code,
    updatedCode,
    diff: validation.diff,
  };
}

module.exports = { analyzeCode };
